### ISSUE TITLE
Beeline users can't resolve tp.internet.beeline.ru

### ISSUE THREAD

**Issue by alardus** [alardus/portaller#16]

**Comment by kruftik** [comment]
этот адрес резолвится только внутренними (10.x.x.x.x/8) днс-ами внутри сети билайна. фиксированно возвращать резолв - очень стремно, т.к. они часто меняются.

**Comment by alardus** [comment]
Есть пара идей. Во-первых, попытаться поговорить с Билайном, узнать список возможных адресов и прописать для них зону. Эпизодически подновлять.

Другой вариант - получать список адресов от кого-то из лояльных пользователей и также эпизодически их подновлять.

**Comment by alardus** [comment]
Похоже, что они не только часто меняются, но еще и различаются в разных сегментах сети (в Москве будут одни, в других городах - другие).
