### ISSUE TITLE
Support for disneyjunior.com / go.com

### ISSUE THREAD

**Issue by fredrike** [alardus/portaller#18]

**Comment by alardus** [comment]
Added, please test it. To point your dnsmasq use:
```
server=/www.go.com/107.170.15.247
server=/www.disneyjunior.com/107.170.15.247
```

**Comment by alardus** [comment]
Fredrike, is it works for you? :)

**Comment by fredrike** [comment]
Disney works fine! Not sure why abc.go.com doesn't.

Have tried to debug but my computer are requesting so many hostnames. Disneyjr is ok for now.

Thank you!

**Comment by alardus** [comment]
When you use local dnsmasq it resolves only those hostnames which you set in config. 
Try to add abc.go.com to config.

**Comment by fredrike** [comment]
Added abc.go.com but still dosen't work.

**Comment by alardus** [comment]
@fredrike Oh, I see the same error now. Will dig it deeper, thanks.
