### ISSUE TITLE
Working out of Hulu support

### ISSUE THREAD

**Issue by kruftik** [alardus/portaller#23]
Are there any thoughts on incorporation of Hulu support to the service ?

In this topic I suggest considering and looking for the possible ways.

**Comment by alardus** [comment]
Nop, just don't have a Hulu account :) Added it to config, can you please test it?

**Comment by alardus** [comment]
Yeah, not so easy https://yadi.sk/i/lZZdN-qofmC3z

**Comment by kruftik** [comment]
Year, they have one of the most comprehensive proxy lists and IP ranges of vps providires :)

anyway, i've got my own nano vps in the u.s. located outside the digital ocean. i'll check whether its address presents in the hulu base.

**Comment by kruftik** [comment]
unfortunately, the vps address is also in the hulu lists :(

**Comment by alardus** [comment]
Seems like it's can't be done in DO VPS. I have played also with http://releasegeo.hulu.com/geoCheck and successfully spoofed it (I think that they use it for extra check) but all this things is nothing without US IP which is not blacklisted.
