### ISSUE TITLE
Create app for mac with autoconfiguration 

### ISSUE THREAD

**Issue by idoo** [alardus/portaller#24]
I think will be really cool if you create app for mac (menubar) with autoconfiguration and on/off mode  :)

**Comment by alardus** [comment]
Simplest one https://www.dropbox.com/s/nd3q9yuwvxdfsmr/RadioTower.zip?dl=0. 
Looks a little bit crappy, but works :) Try it.

**Comment by alardus** [comment]
Some improvements https://www.dropbox.com/s/n8ld59oggounm20/RadioTower-65.zip?dl=0
