### ISSUE TITLE
Amazon Fire TV / TV Stick support

### ISSUE THREAD

**Issue by kruftik** [alardus/portaller#26]
It seems to be a good idea to implement the support of the Amazon Fire TV / TV Stick.

I've just got the one from US Amazon via a mail-forwarder service and after initial connection (to both a WiFi and Amazon account) it recognized me as German user of Amazon.de. It's completely wrong since my A account has been registered to american shipping address.

As it's seen below, the 1st Amazon's address is already German one. Just a reboot hasn't been force it to resolve any additional addresses. In the week I'll try to factory reset the Stick and to compare the addresses list is being resolved immediately after.

**The full list of addresses resolved by the Stick is following:**
 A? 2.android.pool.ntp.org.
 AAAA? spectrum.s3.amazonaws.com.
 AAAA? ntp-g7g.amazon.com.
 A? spectrum.s3.amazonaws.com.
 A? ntp-g7g.amazon.com.
 AAAA? www.amazon.com.
 A? www.amazon.com.
 AAAA? prime.amazon.eu.
 A? prime.amazon.eu.
 AAAA? ktpx-eu.amazon.com.
 AAAA? ktpx-eu.amazon.com.
 A? ktpx-eu.amazon.com.
 AAAA? ktpx-eu.amazon.com.
 AAAA? atv-eu.amazon.com.
 A? atv-eu.amazon.com.
 AAAA? aax-eu.amazon-adsystem.com.
 A? aax-eu.amazon-adsystem.com.
 AAAA? df9v6ngw2bw7n.cloudfront.net.
 A? df9v6ngw2bw7n.cloudfront.net.
 AAAA? clients3.google.com.
 A? clients3.google.com.
 AAAA? messaging-director-us-east-1.amazon.com.
 A? messaging-director-us-east-1.amazon.com.
 AAAA? transponder.amazon.de.
 A? transponder.amazon.de.
 AAAA? ktpx-eu.amazon.com.
 AAAA? cs-ext-eu.amazon.com.
 A? cs-ext-eu.amazon.com.
 AAAA? dp-gw-na.amazon.com.
 A? dp-gw-na.amazon.com.
 AAAA? www.amazon.com.
 A? www.amazon.com.
 AAAA? d21m0ezw6fosyw.cloudfront.net.
 A? d21m0ezw6fosyw.cloudfront.net.
 AAAA? device-messaging-na.amazon.com.
 A? device-messaging-na.amazon.com.
 AAAA? www.amazon.com.
 AAAA? www.amazon.com.
 AAAA? todo-ta-g7g.amazon.com.
 A? todo-ta-g7g.amazon.com.
 AAAA? dp-rsm-prod.amazon.com.
 A? dp-rsm-prod.amazon.com.
 A? spectrum.s3.amazonaws.com.
 AAAA? dp-gw-na.amazon.com.

**Comment by kruftik** [comment]
Passing all the requests to *.amazon.com as well as *.amaznaws.com through dns-proxy (only SNI-enabled without any additional tricks) and factory reset enabled to be US Amazon user. I'm still going to check the needed addresses list more precisely.

**Comment by alardus** [comment]
@kruftik do you have news about this? If it still actual - which domains is needed? :)

**Comment by kruftik** [comment]
I don't have the Stick anymore :( As far as I remember, the the 'US'
access is required only at the time of the 1st boot after each factory
reset. Subsequent work is possible without any proxy or DNS tricks.

2016-01-09 17:40 GMT+05:00, Alexander Bykov <notifications@github.com>:
> @kruftik do you have news about this? If it still actual - which domains is
> needed? :)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alardus/portaller/issues/26#issuecomment-170236384


-- 
С уважением, Дмитрий

тел. +7 (982) 604-50-08
skype:kruftik

**Comment by alardus** [comment]
No Fire TV stick - no fix :)
