### ISSUE TITLE
Spotify problem

### ISSUE THREAD

**Issue by MikeVL** [alardus/portaller#27]
Web client works fine, but the Mac OS client not working.

**Comment by starikovvm** [comment]
![2015-06-18 0 32 28](https://cloud.githubusercontent.com/assets/6888015/8219299/b9801fd6-1551-11e5-957b-6ee9800cb51b.png)
I have set US in profile

**Comment by alardus** [comment]
В Spotify можно залогиниться двумя способами - через акаунт на самом Spotify или через Facebook. Если вы используете акаунт на FB в профиле которого указана страна отличная от US, вам откажут в сервисе - то самое красное сообщение в комментарии выше. 

Используйте вместо него акаунт на самом Spotify - в этом случае страна проверяется только при создании акаунта, после чего клиент может слушать музыку откуда угодно при соблюдении одного из двух условий:
- заходить раз в две недели в свой акаунт с территории US или
- заплатить за premium подписку


*Чтобы не гонять через себя весь трафик, я проксирую только те домены Spotify, которые нужны для создания и управления акаунтом. Все остальное взаимодействие с сервисом (включая прослушивание музыки через клиент) идет напрямую между клиентом и сервером, без проксирования.*

**Comment by starikovvm** [comment]
Спасибо! Создал новый аккаунт - заработало!

**Comment by MikeVL** [comment]
У меня аккаунт не привязан к фейсбуку. С настройками dnsmasq на сайте логинюсь без проблем, а вот приложение не хочет.

Может быть не хватает какого- то домена http://portaller.com/setup#dnsmasq ?

**Comment by alardus** [comment]
@MikeVL а что говорит приложение? Если прописать только 107.170.15.247 на компьютере и почистить системный кеш днс - будет работать или нет?

**Comment by MikeVL** [comment]
Говорит что страна отличается. Проблема появилась где-то с месяц, до того всё работало хорошо. Сейчас делаю вход-выход, всё проходит, видимо раз в две недели страна проверяется.

**Comment by alardus** [comment]
Да, после в входа  акаунт из US две недели страна не проверяется (либо проверяется, но им всё равно). Через две недели нужно снова заходить в акаунт из US или переходить на premium.

**Comment by MikeVL** [comment]
Ладно, фиг с ним. Буду раз в две недели логиниться через VPN

**Comment by alardus** [comment]
Можно просто на сайт сходить - он будет думать, что вы в US.

**Comment by MikeVL** [comment]
На сайте всё хорошо, а в приложении своя авторизация
