### ISSUE TITLE
Spotify - отдаются реальные адреса

### ISSUE THREAD

**Issue by RealFatCat** [alardus/portaller#43]
Привет.
spotify.com резолвится в реальные адреса.
```
$ dig @107.170.15.247 spotify.com +short
194.132.198.228
194.132.198.165
194.132.197.147
$ dig @107.170.15.247 pandora.com +short
107.170.15.247
```

**Comment by alardus** [comment]
Так и должно быть - Spotify "из Штатов" требуется только регистрация, поэтому сделан редирект для www.spotify.com. 

При дальнейшем прослушивании он допускает, что человек может путешествовать и отдает контент независимо от страны в которой находится пользователь. Некоторых, правда, иногда начинает усиленно пушить переходить на Премиум-акаунты :(
