### ISSUE TITLE
mysqueezebox.com support

### ISSUE THREAD

**Issue by Lokydoki** [alardus/portaller#45]
Hi folks, 

First, thanks for the awesomeness of portaller :) 

I've been trying to  use the Logitech Media Server (LMS) with Pandora plugin to no avail...
I have now a RPI3 with dietpi and squeezebox (server ) and squeezelite (player) installed.

Even though i force dns on my squezzebox server and player, I keep getting error because country is not supported by pandora.
What I discovered from tcpdump is that the plugin communicates with http://www.mysqueezebox.com/api/pandora (POST with mysqueezebox credentials, mac adress and so on)
which send the error back ("country not supported"). It is very likely that this api do an IP region verification.

I was wondering if you could add "www.mysqueezebox.com" to portaller to route everything from your servers. I do think that this verification is only on connection initiation.

I'll try to help as much as I can but my knowledge in python is quite inexistant. I just couldn't even figure if this github hosts all the portaller code ...

**Comment by alardus** [comment]
Just added lines that you wrote to portaller configs. Let's try!

**Comment by Lokydoki** [comment]
Hi Alardus, will try tonight. I'll keep you informed :)
