### ISSUE TITLE
Pandora doesnt work

### ISSUE THREAD

**Issue by novakin** [alardus/portaller#49]
Hi,

Thanks for the free awesome service. Everything works except Pandora.

I visited pandora once (dont know if it changes anything) and then knew about Portaller. Even after changing DNS, clearing dns cache and evrything, I still get the "Pandora is not available in your country"page.

I have checked Netflix, Amazon, Spotify, i dont have any problems

**Comment by alardus** [comment]
Hey!
Let's check your settings. 
- What DNS addresses do you use?
- What terminal returns on command 'dig pandora.com'?

**Comment by novakin** [comment]
Hi
Look like it bugged for me the first time, I have rechecked this morning and it is working fine.

Wonderfull  job @alardus
