### ISSUE TITLE
Сервис работает?

### ISSUE THREAD

**Issue by ghost** [alardus/portaller#50]
Добрый день,

Не работает на Spotify клиенте под MacOS, и на IOS, стандартная ошибка: Error code 408

**Comment by John677** [comment]
Подтверждаю, у меня тоже перестало работать

**Comment by DenLeo** [comment]
Долгое время пользовался для прослушивания Spotify, а сегодня со всех устройств выкинуло. Пишет, что больше 14 дней мол в разъездах, т.е. долгое время находился за пределами США

**Comment by aekv** [comment]
Сервис умер

**Comment by bduisenov** [comment]
😭

**Comment by nosovk** [comment]
работает, Яндекс DNS умер - это да.
