### ISSUE TITLE
pandora problem

### ISSUE THREAD

**Issue by demlak** [alardus/portaller#55]
Hi,
first: thx for this great work!

Second:
Pandora has ssl change and there is a problem now:

[Pianobarfly](https://github.com/nega0/pianobarfly) says:
`(i) Login... Network error: Connection closed by remote host.`

And [Pithos](https://pithos.github.io) in verbose mode says:
`ssl.CertificateError: hostname 'tuner.pandora.com' doesn't match 'dynip.space'`

btw: http://portaller.com/status says error 500

**Comment by deewakar** [comment]
[Pianobar](https://github.com/PromyLOPh/pianobar) throws similar error message
```Login... Network error: SSL peer certificate or SSH remote key was not OK```

**Comment by alardus** [comment]
Thanks for report. Made some changes right now, could you please try again?

**Comment by deewakar** [comment]
@alardus Thanks, its working for me. Also, thank you very much for maintaining portaller.

**Comment by alardus** [comment]
@deewakar Thanks for being using!

**Comment by demlak** [comment]
tried it and it works perfect! Thx a lot!

**Comment by demlak** [comment]
Again, same Problem with Pithos.

Pianobarfly now says:
`(i) Login... Network error: File not found.`

**Comment by alardus** [comment]
@demlak fixed :-\

**Comment by demlak** [comment]
Works again. thx a lot =)
