### ISSUE TITLE
It doesn't work anymore on Netflix

### ISSUE THREAD

**Issue by yuhuangniu** [alardus/portaller#59]
After I replaced my DNS with 107.170.15.247 and 77.88.8.8, things still can't play on Netflix. Error [M7111](https://help.netflix.com/en/node/53047) remains.

So any suggestions to fix it? Is this service still in usage?

**Comment by alardus** [comment]
Nope, Netflix is unsupported for now because it have blocked most of VPS networks (mine at Digital Ocean too) that was used for proxying. You can try paid VPN as option, Express/Nord says that they keeping works with Netflix.
