### ISSUE TITLE
Is Portaller down?

### ISSUE THREAD

**Issue by krehman** [alardus/portaller#60]
Apologies in advance if it has been addressed somewhere. Portaller DNS (107.170.15.247) appears to be down.

**Comment by alardus** [comment]
Hi and thank you for notice. Sadly I haven't enough time to operate it and implement features that will helpfull to fight against blocking from Netflix, Pandora and others. So, I made decision to shut Portaller off ans stop suffer about 'it is not working again' and again and again. Now you need to switch you DNS server address back to your ISP or use Google.

**Comment by demlak** [comment]
so.. no chance for getting pandora work in germany? =(

**Comment by alardus** [comment]
I recommend to use one of VPN services that widely available now or setup your own on a small (or conversely very big) vps hosting like amazon - just because their subnet not banned by services (Netflix, Hulu, Pandora) compared to DigitalOcean or other providers.

**Comment by krehman** [comment]
@alardus thanks for the update. How can I compile this code on a Linux server? What are the required components/steps?

**Comment by demlak** [comment]
@alardus 
first: thx for your very helpfull service over years!

i'm not that good to manage my own server.. also i used the pandora+portaller combination because it was without any costs for me. 
when it comes into costs, i also could use other services like spotify.. 

well.. right now, i don't know what my future-way will be..

**Comment by hacker1024** [comment]
> @alardus
> first: thx for your very helpfull service over years!
> 
> i'm not that good to manage my own server.. also i used the pandora+portaller combination because it was without any costs for me.
> when it comes into costs, i also could use other services like spotify..
> 
> well.. right now, i don't know what my future-way will be..

Windscribe has a great free VPN plan

**Comment by nosovk** [comment]
you may try https://github.com/PromyLOPh/pianobar which works with any http proxy, without vpn (music will be not loaded via proxy, only playlist fetched by prox)

**Comment by demlak** [comment]
thx.. i'm using https://github.com/nega0/pianobarfly
But i don't have a working https-proxy

**Comment by alardus** [comment]
> @alardus thanks for the update. How can I compile this code on a Linux server? What are the required components/steps?

No compiling is needed, but you need to do few things:
1) setup your own vps in USA region at a hosting provider which subnet is not blocked by pandora / netflix / hulu or other service that you need to use
2) setup your dns service and override zones - each services has own domains, investigation is needed. as example for pandora this is pandora.com and tuner.pandora.com
3) setup sniproxy (or haproxy) service for proxying data between original services and your vps
4) switch devices to use your dns service

Configs are available at Portaller sources.

**Comment by Lokydoki** [comment]
@alardus  Thank you for all your nice work on portaller. Was a nice and neat idea and this solution helped me and a lot to use a simple dns proxy.
I was wondering if you could help on porting your solution to docker. This could be a great why to make portaller still be used without you having to maintain (and paying...) the VPS that holds all the magic ?
From my understanding, to adapt your step by steps, this would be like : 
1.setup your own vps in USA region at a hosting provider which subnet is not blocked by pandora / netflix / hulu or other service that you need to use
2.install docker 
3.pull docker image of portaller
4.start container ?
5.switch devices to use dns service
6.profit !!?

For now I can see on this repo that we need on that container  : 
bind
fail2ban --> is it really needed ?
haproxy / sniproxy ?
nginx  --> is it really needed ?

Those would be installed from docker build and configuration would come from a pull from github/alardus/portaller

**Comment by Termicj** [comment]
Доброго дня. Сделал бы кто инструкцию, для людей которые не так хорошо разбираются в линуксах, а для личного пользования или для нескольких друзей хотелось бы иметь доступ до Пандоры

Good day. Someone would do instructions for people who are not so good at Linux, but for personal use or for a few friends I would like to have access to Pandora
